### ISSUE TITLE
 [bug]

### ISSUE THREAD

**Issue by Morty-Mortee** [douglasZwick/blb#7]
**Describe the bug**
When I play the level (press tab) the game functions until I press tab again. The screen goes black and when I press tab again, you can see the level for a single second (in the instance you press tab) but the screen remains black.

**Tell us how to reproduce it**
Please provide a list of steps to reproduce the behavior:
1. Open the BLB.
2. Make a few platforms. The level isn't big - about 7 platforms, spaced however in whatever length.
3. Make sure there is a player and at least 1 platform with a path in use.
4. Press tab. 
5. Press tab again.

The screen should turn black. It may take a few playthroughs.

**Tell us the expected behavior**
The editor should exit playtest mode. 

![error_](https://user-images.githubusercontent.com/60281468/73116213-63be3a00-3ee7-11ea-9ef1-3e67afddf57f.PNG)

**Tell us about the version you're using**
Please provide the following version information:
 - Platform: Desktop - this problem exists on school computers and my own laptop (Dell).
  - I'm not using web browser.
 - Version v0.9.40

**Do you have any additional insight?**
This prevents me from doing an des301 work with this build, so I am going to use an older build. It appears to only occur when you use any platform with any path function.

**Comment by douglasZwick** [comment]
Good catch. For future reference, the problem was with any path that consisted of only "zero nodes" — that is, all of its nodes were placed at the same position as the anchor point used by the Path Tool. (This could be a single node or more than one.) When I ran it in the editor, and I tried to go back to edit mode from play mode, I saw that there was actually a null reference exception in the console, and I was able to quickly pinpoint the problem and fix it.
